### ISSUE TITLE
sum() did not return right value.

### ISSUE THREAD

**Issue by aldesrahim** [Flowframe/laravel-trend#14]
I've a `datetime` column named `date`, I want to get sum of `total` using `perDay` and `perMonth`, but it seems not giving the right value.

Please take a look at this specific line of code:
https://github.com/Flowframe/laravel-trend/blob/dd00920b628e6e9655aeb6c59921248ee8ff0937/src/Trend.php#L94

Imo, it should be like this:
`->groupByRaw($this->getSqlDate())`

because while using perMonth or perDay, it no grouping rows by the formatted column like `date_format(date, '%Y-%m')` instead it group using column like `date`.

In this case, rows with same same day or month not summing up the `total`.

Edit:
Here is the query of given example above using `perDay` method:
```
select 
date_format(date, '%Y-%m-%d') as date,
sum(total) as aggregate
from `sales` where `date` between '2022-05-23 00:00:00' and '2022-05-30 23:59:59' group by `date` order by `date` asc
```
if I have 2 records within the same day but different hour, it will return 2 record and not summed up the total.

Info:
Laravel 9, MySQL, Apache

I am sorry for my bad English. Hope you all can understand what I am trying to say. Thank you !

**Comment by haheap** [comment]
I haven’t tested it, but I suspect it’s related to #8 and issues when the table has a field named ‘date’. I’ve submitted a PR awaiting approval: https://github.com/Flowframe/laravel-trend/pull/13

**Comment by aldesrahim** [comment]
Ah, I have noticed that. Maybe it because I have a column named `date` so when the query builder trying to group by 'date' it refers to my column named `date` instead of the alias.

**Comment by magarrent** [comment]
Hey there! This issue was solved? I think the sum() function is not working:

![image](https://user-images.githubusercontent.com/6561770/221212601-feb90447-9b9c-4e8c-8786-141ef450122e.png)

![image](https://user-images.githubusercontent.com/6561770/221212667-4dbe2751-2183-4b5f-9d04-1413a7dda42b.png)

![image](https://user-images.githubusercontent.com/6561770/221212739-4320b1f2-026a-47d8-8fb7-fca0c349ab4b.png)
