### ISSUE TITLE
Problem with "kirschbaum-development/eloquent-power-joins" package

### ISSUE THREAD

**Issue by aldesrahim** [Flowframe/laravel-trend#15]
Hi, I have notice when using `eloquent-power-joins` can cause query problem.

So, `eloquent-power-joins` is using scope to simplify `join` query between relations, please take a look at this particular [line of codes](https://github.com/kirschbaum-development/eloquent-power-joins/blob/98e0ecc6844014a0169115ebea9985a89bbc61f2/src/PowerJoins.php#L40-L42). If you notice, it will check if query has `select`, if not it will add `SELECT *` to query.

Since `laravel-trend`'s `aggregate` method using `selectRaw`, the code I've shown (line 40) will return false, and add `SELECT *` to query, it cause problem since `laravel-trend` using `groupBy` to find aggregate columns.

I have solution for this problem by replacing [this](https://github.com/Flowframe/laravel-trend/blob/dd00920b628e6e9655aeb6c59921248ee8ff0937/src/Trend.php#L89-L92) with this:
```
->select([
    DB::raw("{$this->getSqlDate()} as date"),
    DB::raw("{$aggregate}({$column}) as aggregate"),
])
```

I am sorry for my bad english, I hope you all can understand what I am trying to say. Thank you !

Info:
Laravel 9, MySQL

**Comment by Larsklopstra** [comment]
Closing stale issue
