### ISSUE TITLE
Invalid column reference when trying to fetch distinct column

### ISSUE THREAD

**Issue by humaneguy** [Flowframe/laravel-trend#21]
### Problem description

When trying to retrieve unique attendees of an event. I'm using this query:
```php
Attendee::query()->distinct('user_id')
```

It works on its own but when using it in this chart widget;
```php
Trend::query(Attendee::query()->distinct('user_id'))
            ->between(
                start: now()->setDate(2021, 1, 1),
                end: now(),
            )
            ->perMonth()
            ->count();
```

I get this error:

```
SQLSTATE[42P10]: Invalid column reference: 7 ERROR: SELECT DISTINCT ON expressions must match initial ORDER BY expressions LINE 1: select distinct on ("user_id") ^ (SQL: select distinct on ("user_id") to_char(created_at, 'YYYY-MM') as date, count(*) as aggregate from "attendees" where "created_at" between 2021-01-01 16:43:04 and 2022-10-14 16:43:04 group by "date" order by "date" asc)
```

**Comment by Larsklopstra** [comment]
Closing stale issue

**Comment by vpuentem** [comment]
Did you manage to get it? I'm trying to do something similar with no results :/

**Comment by otilor** [comment]
Can't really remember. I think I did tho'. No longer have access to the codebase.

**Comment by vpuentem** [comment]
This works apparently, if you look at the _aggregate()_ method used by the count(), sum(), etc. It uses the column name and the aggregate in a string, so you can pass different values depending on what you need

`
Trend::query(Attendee::query())
            ->between(
                start: now()->setDate(2021, 1, 1),
                end: now(),
            )
            ->perMonth()
            ->count('DISTINCT user_id');
`

**Comment by otilor** [comment]
Ok. Thank you.

**Comment by MCKLtech** [comment]
@vpuentem , thank you, this worked for me.
