### ISSUE TITLE
duration aggregate

### ISSUE THREAD

**Issue by FrodeMMeling** [Flowframe/laravel-trend#29]
Is it possible to aggregate on a duration in minutes between two timestamps. Like using MYSQL TIMESTAMPDIFF

**Comment by FrodeMMeling** [comment]
I was able to hack this in by doing this:
`->aggregate('HOUR, login_time, logout_time)', 'SUM(TIMESTAMPDIFF');`
If aggregate function could take more parameters this would work.
A timestamp function may not be added since that is not supported in all databases.

**Comment by Larsklopstra** [comment]
Seems like you've found a workaround.
