### ISSUE TITLE
weekly range?

### ISSUE THREAD

**Issue by Malebestia** [Flowframe/laravel-trend#32]
in the documentation it says:
Interval
You can use the following aggregates intervals:
      perMinute()
      perHour()
      perDay()
      perMonth()
      perYear()

Is there a weekly one? did you forget it or are you implementing it?

**Comment by kaiserification** [comment]
same here

**Comment by Larsklopstra** [comment]
This issue has been brought up before, databases yield different results. There's no solution which satisfies me yet. The problem is that some count weeks per month, and others count weeks per year.

**Comment by ChrisHardie** [comment]
@Larsklopstra do you have any pointers for those of use who might need to implement this ourselves / extend the package?
