### ISSUE TITLE
Conditional aggregates or intervals

### ISSUE THREAD

**Issue by vpuentem** [Flowframe/laravel-trend#41]
I'm trying the apply different aggregates based on filters, like "daily" applies a perDay() and "monthly" applies a perMonth() aggregate, could be something similar to the when() condition en eloquent, for example:

`
Trend::query(Model::where('condition', true))->between(
start: $startDate,end: $endDate)
->when(
        $activeFilter == 'daily', fn ($query) => $query->perDay()
    )
`

Is there a way to do it?

**Comment by swthate** [comment]
Any word on this yet?

**Comment by vpuentem** [comment]
Thanks, i think that should work
