### ISSUE TITLE
Request: add `perWeek` interval

### ISSUE THREAD

**Issue by sunxyw** [Flowframe/laravel-trend#7]
It will be great if you can add support for the `perWeek` interval.

**Comment by kurucu** [comment]
This would be easy, but it might be a breaking change.`CarbonPeriod` accepts text for interval, and would accept e.g. "7 days".
But, the way that it's currently coded, "interval" accepts any singular period and then appends it to "1 ". I think the cleanest way to make the change is have the library just accept any loose text and pass it straight to CarbonPeriod.

Then the preset methods would read e.g.:

```
public function perYear()
{
    $this->interval = '1 year';
}

public function perWeek()
{
    $this->interval = '7 days';
}
```
