### ISSUE TITLE
Raw date

### ISSUE THREAD

**Issue by ju5t** [Flowframe/laravel-trend#8]
The package uses `{$this->getSqlDate()} as date,` in its query builder. We have some models with a `date` column already so we get a SQL error when using this package.

Can we either make this configurable or use a different default? I don't think it's a breaking change as the public data is in `TrendValue` but if I'm wrong just let me know :)

**Comment by haheap** [comment]
I encountered the same issue.

 I'd be glad to do a PR to make it configurable - and possibly with a different default to make it even less likely for someone to encounter the issue in the first place.
